name: Build & Push (GHCR)
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/smart-inventory-api:latest

      - name: Build & push WEB
        uses: docker/build-push-action@v6
        with:
          context: ./apps/web
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/smart-inventory-web:latest
